package zealot.http.cookie

import better.files.File
import zealot.commons.ZLT
import zealot.http.{DefaultResponseCookie, HttpContext, HttpEnvironment, ResponseCookie}
import zio.*

import java.net.URI
import java.time.{ZoneId, ZonedDateTime}
import scala.util.Try

sealed trait CookieJar {
  def all                     : Set[ResponseCookie]
  def byDomain(domain: String): Set[ResponseCookie]
}

object CookieJar {
  def make(cookies: Set[ResponseCookie])(using ctx: HttpContext): Task[CookieJar] = ZIO.attemptBlocking {
    val file = ctx.root / "cookies.txt"
    file.touch()
    NetscapeCookieFile.write(file, cookies)
    CurlCookieJar(file)
  }
}


case class CurlCookieJar(file: File) extends CookieJar {

  override def all: Set[ResponseCookie]                      = NetscapeCookieFile.read(file)
  override def byDomain(domain: String): Set[ResponseCookie] = all.filter(c => NetscapeCookieFile.matches(domain, c))
}

/**
 * Reads and writes the Netscape "cookies.txt" file format used by curl's
 * --cookie / --cookie-jar flags.
 *
 * Format: 7 tab-separated columns per line.
 *   1. domain               (host or .domain.tld; "#HttpOnly_" prefix marks HttpOnly)
 *   2. include-subdomains   (TRUE for domain cookies, FALSE for host-only)
 *   3. path                 (defaults to "/")
 *   4. secure               (TRUE / FALSE)
 *   5. expires              (unix epoch seconds; 0 means session cookie)
 *   6. name
 *   7. value
 *
 * Lines starting with "#" are comments. Empty lines are ignored.
 *
 * See: https://curl.se/docs/http-cookies.html
 */
object NetscapeCookieFile {

  private val HttpOnlyPrefix = "#HttpOnly_"

  private val Header =
    """# Netscape HTTP Cookie File
      |# https://curl.se/docs/http-cookies.html
      |# This file was generated by zealot. Edit at your own risk.
      |""".stripMargin

  def read(file: File): Set[ResponseCookie] = {
    if (!file.exists) Set.empty
    else file.lineIterator
      .map(_.trim)
      .filter(line => line.nonEmpty)
      .flatMap(parseLine)
      .toSet
  }

  def write(file: File, cookies: Iterable[ResponseCookie]): Unit = {
    val body = cookies.map(formatLine).mkString("\n")
    file.overwrite(Header + body + (if (body.nonEmpty) "\n" else ""))
  }

  /**
   * RFC 6265 §5.1.3 host/domain matching driven by the `hostOnly` flag.
   * - hostOnly = true  : request host must equal cookie domain (case-insensitive).
   * - hostOnly = false : request host must equal OR be a subdomain of cookie domain.
   */
  def matches(requestHost: String, cookie: ResponseCookie): Boolean = {
    cookie.domain match {
      case None    => false
      case Some(d) =>
        val bare = d.stripPrefix(".").toLowerCase
        val host = requestHost.toLowerCase
        if (cookie.hostOnly) host == bare
        else                 host == bare || host.endsWith("." + bare)
    }
  }

  private def parseLine(line: String): Option[ResponseCookie] = {
    if (line.startsWith("#") && !line.startsWith(HttpOnlyPrefix)) None
    else {
      val cols = line.split('\t')
      if (cols.length < 7) None
      else {
        val (rawDomain, httpOnly) =
          if (cols(0).startsWith(HttpOnlyPrefix)) (cols(0).drop(HttpOnlyPrefix.length), true)
          else                                    (cols(0)                            , false)

        val includeSub = cols(1).equalsIgnoreCase("TRUE")
        val path       = cols(2)
        val secure     = cols(3).equalsIgnoreCase("TRUE")
        val expires    = Option(cols(4)).flatMap(s => Try(s.toLong).toOption).filter(_ > 0)
        val name       = cols(5)
        val value      = cols(6)

        // Column 2 carries the host-only-vs-domain distinction. Strip any
        // leading dot from column 1 so `domain` always holds the bare
        // canonical value (RFC 6265 §5.2.3 / §5.3 step 6).
        val bareDomain = rawDomain.stripPrefix(".")

        Some(DefaultResponseCookie(
          url      = "",
          name     = name,
          value    = value,
          domain   = Some(bareDomain),
          path     = Some(path),
          hostOnly = !includeSub,
          secure   = Some(secure),
          httpOnly = Some(httpOnly),
          expires  = expires.map(s => ZonedDateTime.ofInstant(java.time.Instant.ofEpochSecond(s), ZoneId.of("UTC")))
        ))
      }
    }
  }

  private def formatLine(cookie: ResponseCookie): String = {

    val rawDomain  = cookie.domain.map(_.stripPrefix(".")).getOrElse(hostOf(cookie.url).getOrElse(""))
    val includeSub = !cookie.hostOnly
    val prefix     = if (cookie.httpOnly.contains(true)) HttpOnlyPrefix else ""
    val path       = cookie.path.getOrElse("/")
    val secure     = if (cookie.secure.contains(true)) "TRUE" else "FALSE"
    val includeStr = if (includeSub) "TRUE" else "FALSE"
    val expires    = cookie.expires.map(_.toEpochSecond.toString).getOrElse("0")

    Seq(
      prefix + rawDomain,
      includeStr,
      path,
      secure,
      expires,
      cookie.name,
      cookie.value
    ).mkString("\t")
  }

  private def hostOf(url: String): Option[String] = {
    if (url.isEmpty) None
    else Try(new URI(url).getHost).toOption.filter(_ != null)
  }
}
